apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reverse-tender.fullname" . }}-secret
  labels:
    {{- include "reverse-tender.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.app }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
